/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    // "aws_cognito_identity_pool_id": "eu-central-1:5e90e230-b3ec-42a3-b637-c980c2fbfea7",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_5dPr5OFej",
    "aws_user_pools_web_client_id": "1u6887q3i6qesbhummej0gs735",
    "oauth": {
        "domain": "http://localhost:4200/",
        "scope": [
            "phone",
            "email",
            "name",
            "profile_type",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:4200/",
        "redirectSignOut": "http://localhost:4200/home-page",
        "responseType": "code"
    }
};


export default awsmobile;
